const { Router } = require("express");
const authRoute = require("./authRoutes");
const storageRoutes = require("./storageRoutes");
const storageUnitRoutes = require("./storageUnitRoutes");
const pricingProfileRoutes = require("./pricingProfileRoutes");
const profileRoutes = require("./profileRoutes");
const bookingRoutes = require("./bookingRoutes");
const meetingRoutes = require("./meetingRoutes");
const documentRoutes = require("./documentRoutes");
const oauthRoutes = require("./oauthRoutes");
const advertisementRoutes = require("./advertisementRoutes");
const healthCheckRoute = require("./healthCheckRoutes");
const apiLogsRoute = require("./apiLogsRoutes");
const roleRoutes = require("./roleRoutes");
const notificationRoutes = require("./notificationRoutes");
const paymentRoutes = require("./paymentRoutes");
const imageRoutes = require("./imageRoute");
const bookmarkRoutes = require("./bookmarkRoutes");
const recommendedRoutes = require("./recommendedPropertyRoutes");

const router = Router();

router.use("/", healthCheckRoute);
router.use("/api-logs", apiLogsRoute);
router.use("/auth", authRoute);
router.use("/storage-properties", storageRoutes);
router.use("/storage-units", storageUnitRoutes);
router.use("/pricing-profiles", pricingProfileRoutes);
router.use("/profile", profileRoutes);
router.use("/bookings", bookingRoutes);
router.use("/meetings", meetingRoutes);
router.use("/documents", documentRoutes);
router.use("/oauth", oauthRoutes);
router.use("/advertisements", advertisementRoutes);
router.use("/roles", roleRoutes);
router.use("/notifications", notificationRoutes);
router.use("/payments", paymentRoutes);
router.use("/remove-image", imageRoutes);
router.use("/bookmarks", bookmarkRoutes);
router.use("/recommended", recommendedRoutes);

module.exports = router;
