// Notification Priority Enum
const NOTIFICATION_PRIORITY = {
  HIGH: "High",
  MEDIUM: "Medium",
  LOW: "Low",
};

const NOTIFICATION_STATUS = {
  UNREAD: "Unread",
  READ: "Read",
};

const NOTIFICATION_TYPE = {
  // Property & Unit Setup
  PROPERTY_CREATED: "PROPERTY_CREATED",
  UNIT_CREATED: "UNIT_CREATED",
  UNIT_PUBLISHED: "UNIT_PUBLISHED",
  UNIT_VIEWED: "UNIT_VIEWED",

  // User Interest & Booking
  MEETING_REQUESTED: "MEETING_REQUESTED",
  MEETING_REJECTED: "MEETING_REJECTED",
  MEETING_CONFIRMED: "MEETING_CONFIRMED",
  MEETING_COMPLETED: "MEETING_COMPLETED",
  MEETING_REMINDER: "MEETING_REMINDER",

  // Booking
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  BOOKING_INITIATED: "BOOKING_INITIATED",

  // Documents
  DOCUMENTS_UPLOADED: "DOCUMENTS_UPLOADED",
  DOCUMENTS_VERIFIED: "DOCUMENTS_VERIFIED",
  DOCUMENTS_REJECTED: "DOCUMENTS_REJECTED",
  DOCUMENTS_RESUBMISSION_REQUIRED: "DOCUMENTS_RESUBMISSION_REQUIRED",
  DOCUMENTS_RESUBMITTED: "DOCUMENTS_RESUBMITTED",

  BOOKING_ACTION: "BOOKING_ACTION",

  // Cash Payment Request
  CASH_PAYMENT_REQUESTED: "CASH_PAYMENT_REQUESTED",
  CASH_PAYMENT_APPROVED: "CASH_PAYMENT_APPROVED",
  CASH_PAYMENT_REJECTED: "CASH_PAYMENT_REJECTED",

  // Rental Process
  RESERVATION_APPROVED: "RESERVATION_APPROVED",
  RESERVATION_REJECTED: "RESERVATION_REJECTED",
  PAYMENT_INITIATED: "PAYMENT_INITIATED",
  PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
  CONTRACT_GENERATED: "CONTRACT_GENERATED",
  UNIT_RENTED: "UNIT_RENTED",
  ACCESS_PROVIDED: "ACCESS_PROVIDED",
  CASH_PAYMENT_REQUESTED: "CASH_PAYMENT_REQUESTED",
  CASH_PAYMENT_APPROVED: "CASH_PAYMENT_APPROVED",
  CASH_PAYMENT_REJECTED: "CASH_PAYMENT_REJECTED",

  // Ongoing Rental Management
  MONTHLY_PAYMENT_DUE: "MONTHLY_PAYMENT_DUE",
  PAYMENT_PROCESSED: "PAYMENT_PROCESSED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  RENTAL_EXTENDED: "RENTAL_EXTENDED",
  NOTICE_GIVEN: "NOTICE_GIVEN",

  // Rental Completion
  INSPECTION_SCHEDULED: "INSPECTION_SCHEDULED",
  INSPECTION_COMPLETED: "INSPECTION_COMPLETED",
  SECURITY_DEPOSIT: "SECURITY_DEPOSIT",
  UNIT_VACATED: "UNIT_VACATED",
  UNIT_AVAILABLE: "UNIT_AVAILABLE",

  // Payment & Earnings Timeline
  RENTAL_PAYMENT_RECEIVED: "RENTAL_PAYMENT_RECEIVED",
  EARNINGS_ACCUMULATED: "EARNINGS_ACCUMULATED",
  PAYOUT_REQUESTED: "PAYOUT_REQUESTED",
  PAYOUT_REVIEWED: "PAYOUT_REVIEWED",
  PAYOUT_PROCESSED: "PAYOUT_PROCESSED",
  PAYMENT_REMINDER: "PAYMENT_REMINDER",
  PAYOUT_COMPLETED: "PAYOUT_COMPLETED",
  PAYOUT_REJECTED: "PAYOUT_REJECTED",

  // Advertising Timeline
  AD_SUBMITTED: "AD_SUBMITTED",
  AD_DRAFT: "AD_DRAFT",
  AD_REVIEWED: "AD_REVIEWED",
  AD_PUBLISHED: "AD_PUBLISHED",
  AD_PERFORMANCE: "AD_PERFORMANCE",
  AD_EXPIRED: "AD_EXPIRED",

  // System Notifications
  NEW_USER_REGISTRATION: "NEW_USER_REGISTRATION",
  PROPERTY_APPLICATION: "PROPERTY_APPLICATION",
  PAYMENT_PROCESSING: "PAYMENT_PROCESSING",
  RENTAL_EXPIRY: "RENTAL_EXPIRY",
  SYSTEM_MAINTENANCE: "SYSTEM_MAINTENANCE",
  SECURITY_ALERTS: "SECURITY_ALERTS",


  SUPER_ADMIN_NOTIFICATION: "SUPER_ADMIN_NOTIFICATION",

  RECOMMENDATION_REQUEST: "RECOMMENDATION_REQUEST",
  RECOMMENDATION_REVIEWED: "RECOMMENDATION_REVIEWED",

  SUBSCRIPTION_UPDATED: "SUBSCRIPTION_UPDATED",
};

module.exports = {
  NOTIFICATION_PRIORITY,
  NOTIFICATION_STATUS,
  NOTIFICATION_TYPE,
};
